### ISSUE TITLE
Default brightness keys not working

### ISSUE THREAD

**Issue by GoldenChaos** [fnesveda/ExternalDisplayBrightness#1]
Hey there! This is literally the first app around to allow me to change the brightness of all my monitors simultaneously. Thank you!! Now, onto the issue:

On my external magic keyboard (I can't test with my touch bar mac's built-in keyboard), the app by default does not take command of the normal brightness keys. If I change the keys to F1 and F2, and hold the fn key, the app works properly and the brightness on all my monitors changes.

Perhaps on magic keyboards brightness up/down is not mapped to F14/F15?

Running macOS Catalina 10.15.1 Beta 1, 15" MBP 2018 Vega 20, with two external Ultrafine 5K monitors.

**Comment by fnesveda** [comment]
Hi,
I'm happy to hear the app is useful to you, I was hoping that someone might like it.

Unfortunately I can't test this myself, as I don't own a Magic Keyboard, but it's probable that the mapping is different, and on Magic Keyboards the brightness keys send different keycodes. Could you please try using the [Key Codes app](http://manytricks.com/keycodes/) to see what keycodes are generated by the brightness keys, so I can add them to the app?

Also, just for future reference, what version of the Magic Keyboard are you using?

Thanks,
František

**Comment by GoldenChaos** [comment]
Oddly, the Key Codes app does not show _anything_ when I press _any_ of Apple's labeled function keys.

I'm using a US-layout Magic Keyboard 2:

![](https://images-na.ssl-images-amazon.com/images/I/61cQK1PJvFL._SL1000_.jpg)
![61cQK1PJvFL _SL1000_](https://user-images.githubusercontent.com/1396727/66766387-f75d8480-ee7b-11e9-87c9-c5e763296fb6.jpg)

![](https://images-na.ssl-images-amazon.com/images/I/61cQK1PJvFL._SL1000_.jpg)

**Comment by fnesveda** [comment]
Okay, that probably means that macOS is consuming the special keys before they even have a chance to get to any user app via the standard channels.

Do you have Xcode installed? And if so, could you open and run [this playground](https://github.com/fnesveda/ExternalDisplayBrightness/files/3725597/BrightnessKeysTest.zip), then press the brightness keys and see if there is any output in the playground? I played with generating keycodes in AppleScript and I found out that when you send the keycodes 144 and 145, the brightness of your Mac's internal display changes, so I believe these could be the proper keycodes to listen for, so in the playground, I use some private Apple APIs to listen for keypresses on the system level. 

I'm not sure if this will work, to be honest, but I have hope.

**Comment by GoldenChaos** [comment]
Here's what I got when pressing brightness up and then brightness down (so, four button states):

```
NSEvent: type=SysDefined loc=(1191.88,464.781) time=201717.2 flags=0x800100 win=0x0 winNum=0 ctxt=0x0 subtype=6 data1=123456 data2=0
NSEvent: type=SysDefined loc=(1191.88,464.781) time=201717.3 flags=0x800100 win=0x0 winNum=0 ctxt=0x0 subtype=9 data1=123456 data2=0
NSEvent: type=SysDefined loc=(1191.88,464.781) time=201719.3 flags=0x800100 win=0x0 winNum=0 ctxt=0x0 subtype=6 data1=654321 data2=0
NSEvent: type=SysDefined loc=(1191.88,464.781) time=201720.0 flags=0x800100 win=0x0 winNum=0 ctxt=0x0 subtype=9 data1=654321 data2=0
```

**Comment by fnesveda** [comment]
Alright, that looks very promising, thanks. Did the brightness of any of the displays change when you pressed the keys? We want to hijack the keyboard events completely so they don't get handled by the system at all, otherwise the brightness would be changing twice with the same keypress, once from the system, once from ExternalDisplayBrightness.

I'll probably have to rewrite the keyboard shortcut manager of the app to use this way of listening for shortcuts, but on the off chance that the old system works with the right keycodes, could you please test [this beta version](https://github.com/fnesveda/ExternalDisplayBrightness/files/3726232/ExternalDisplayBrightness-1.1.1-beta2.zip) of the app and set 144 and 145 as the keys in the preferences, and see if it works? I don't think it will, but it would be a pleasant surprise if it did.

**Comment by GoldenChaos** [comment]
Brightness did not change when I pressed the keys.

Your beta version actually works! 145 is Brightness Down, and 144 is Brightness Up it seems.

**Comment by fnesveda** [comment]
Nice, glad to hear that!
I'll clean the code up a bit and release a new stable version soon.

**Comment by fnesveda** [comment]
I've just published a new stable release, 1.2.0, which fixes this, but unfortunately if you're coming from the beta version you'll have to select the proper keys (MK_BDN and MK_BUP) again in the app's preferences for the keyboard shortcuts to work, sorry about that.

**Comment by ajp** [comment]
I have the older aluminum full (including 10key) wired USB keyboard, and it didn't use the default brightness keys either. I was able to get the official F14/F15 keys to work, but wanted to help get the regular keyboard working too.

I ran the sandbox posted above and got the following response from the F1/F2/brightness keys on this keyboard:
`NSEvent: type=SysDefined loc=(353.875,856.438) time=161550.2 flags=0x800100 win=0x0 winNum=0 ctxt=0x0 subtype=6 data1=654321 data2=0
NSEvent: type=SysDefined loc=(353.875,856.438) time=161550.3 flags=0x800100 win=0x0 winNum=0 ctxt=0x0 subtype=9 data1=654321 data2=0
NSEvent: type=SysDefined loc=(632.043,387.551) time=161551.6 flags=0x800100 win=0x0 winNum=0 ctxt=0x0 subtype=6 data1=123456 data2=0
NSEvent: type=SysDefined loc=(632.043,387.551) time=161551.7 flags=0x800100 win=0x0 winNum=0 ctxt=0x0 subtype=9 data1=123456 data2=0`

**Comment by fnesveda** [comment]
@ajp So the MK_BUP and MK_BDN keys don't work? If you got that response from the playground, it should mean the brightness keys on the keyboard are generating keycodes 144 and 145, just like the Magic Keyboard, so I think the same keys selected in the preferences should work.

**Comment by ajp** [comment]
Holy crap, I didn't even notice or try those. It's all working amazing now!

**Comment by GoldenChaos** [comment]
@fnesveda might I suggest changing the name in the UI to something more intuitive? “Magic Keyboard - Brightness Up” for example would be much easier to understand. Could you could also sidestep this issue entirely and automatically switch to the magic keyboard controls if the app detects a magic keyboard is connected?

**Comment by fnesveda** [comment]
I was thinking about the name as well, MK_BUP is not really intuitive, I know. The problem is that the width of the combo box is determined based on the longest selectable value, so it would be super wide even if something short, like F1, would be selected, and there would be a lot of empty space that would look weird. I'll see if it's somehow possible to have a different value displayed in the expanded combobox compared to the collapsed one.

As for sidesteping the issue, that's a good suggestion, but I don't really know if there even is an API to detect the connected keyboard model. Plus I don't even have a Magic Keyboard myself, so it would be pretty hard to test. It would be a very Apple-like way to do things, though.

**Comment by ma-con** [comment]
I just found your little tool and find it really useful.
Unfortunately, selecting the Magic Keyboard keys does not work.

I got a MagicKeyboard with German layout (old one with AA batteries), and using the Karabiner event viewer, the keycodes I see when pressing the brightness keys are 112 and 111. Is there something I can do to make the tool work with those keys?

Thanks!

**Comment by fnesveda** [comment]
@ma-con Hi,

unfortunately, the Karabiner keycodes do not correspond to keycodes reported by the system (I don't know why). Could you please use the [Keycodes app](https://manytricks.com/keycodes/) to find out the system keycodes, or, even better, if you have Xcode installed, run [this playground](https://github.com/fnesveda/ExternalDisplayBrightness/files/3887412/BrightnessKeysTest.zip) to see its output when you press the brightness keys on your keyboard?

Thank you!

**Comment by ma-con** [comment]
Thanks for your help.
For some reason I don't get any output when pressing the function keys, neither from the keycodes app nor from the playground. For other keys I get output, but for the function keys nothing is shown...

**Comment by fnesveda** [comment]
Huh, strange. In the Karabiner Event Viewer, does it also show a name for the pressed keys, or just the keycode?

**Comment by ma-con** [comment]
The output in the Event Viewer is:

```
type:consumer_key_do code:112        name:display_brightness_decrement
type:consumer_key_up code:112        name:display_brightness_decrement
type:consumer_key_do code:111        name:display_brightness_increment
type:consumer_key_up code:111        name:display_brightness_increment
```

**Comment by fnesveda** [comment]
Thanks! I'll have to take a look at how exactly does Karabiner listen for key events to see what do they do differently that they can capture the brightness keys. I took a quick look, but it looks like it's a pretty complex app, so I'll have to dig a bit deeper when I have some time.
