### ISSUE TITLE
[Feature Request] ExternalDisplaySound?

### ISSUE THREAD

**Issue by kevinjohncutler** [fnesveda/ExternalDisplayBrightness#12]
Any chance you might want to implement audio control in addition to brightness? MonitorControl never fixed their numerous issues (with hiding the OSD in particular, but you were able to fix the dual-monitor problem a while ago too). I'm not sure how closely related such an implementation would be to changing brightness, but never hurts to ask.

**Comment by fnesveda** [comment]
Hi,

I agree that this would be cool to have, but unfortunately, I don't have any external displays with built-in speakers, so external display volume control would be quite complicated for me to implement without being able to test it.

For basic functionality, I don't think the implementation would be drastically different, though, it's just keyboard shortcuts and DDC commands again (but I'm sure there would be a lot of caveats which would make this far from straightforward). I believe there would be an issue with the native volume indicator in the menubar, which would not correspond to the volume set on the display, and that would require quite a bit of research to hack and make work.

Anyway, when thinking about this, I found [eqMac](https://github.com/nodeful/eqMac2), which could possibly serve as a workaround, if you wanna give it a shot, but I haven't tried it myself.

I'll close this issue as out of scope for now, but if I ever decide to revisit this idea in the future, I'll reopen it.

Cheers!
