### ISSUE TITLE
Dual Thunderbolt Display brightness doesn't change

### ISSUE THREAD

**Issue by thenib** [fnesveda/ExternalDisplayBrightness#2]
Only shows the brightness adjustment interface while adjusting but no adjustment takes place

**Comment by fnesveda** [comment]
Hi,

just to make sure, you have two displays, each connected by a single Thunderbolt cable, or one display that needs to be connected by two Thunderbolt cables at once to work properly?
If it's two displays, there are some issues with telling the displays apart if they are the same model and they don't report their serial number to the system properly. If it's one display connected with two cables at once, I'm afraid that will be hard for me to fix, as I don't have that kind of display available, and I'm honestly not sure how do the framebuffer ports and their DDC interfaces work in that case. I'll try to figure something out.

Could you please tell me what is the model of the display(s)? And just for future reference, what Mac do you have, and what version of macOS are you running?

Thanks.

**Comment by fnesveda** [comment]
I'm going to close this as there was no reply for over a month, and I've made some changes to multi-display support which could possibly fix the issue. Feel free to come back to me with more info later, I'll be happy to reopen this and try to help.
