### ISSUE TITLE
Behavior when function keys are set as standard function keys

### ISSUE THREAD

**Issue by apaksoy** [fnesveda/ExternalDisplayBrightness#29]
Thank you for this great app! It's a life saver!!!

I am using a Magic Keyboard (external) and an LG 32UN880 monitor (external) along with my four-port 13" 2019 MacBook Pro (macOS 13.5.2) in the clamshell mode. The keyboard function keys, whether on the internal or external keyboard, are set to behave as standard function keys via the option in the MBP's System Settings->Keyboard->Keyboard Shortcuts->Function Keys.

I have set the externalDisplayBrightness app to reduce and increase brightness when F1 and F2 keys are pressed, respectively, through the app's preferences. When I press the F1 and F2 keys now, the screen brightness is decreased and increased, respectively. This is not too bad at all, but I would prefer, when the keyboard function keys are set the way they are now in the system settings, the F1 and F2 keys to change the external display's brightness only if the "fn" modifier key is pressed as well.

I have tried the F1 and F2 keys when the "Require Command modifier to be pressed" option in the app's preferences is turned either on or off. Unfortunately, this option does not seem to have any effect on the behavior of the F1 and F2 keys when they are set to behave as standard function keys.

Apologies if I have not been able to explain my situation clearly enough or this issue has already given you a headache! It is quite alright if this is not something easy to fix as your app has already helping me a lot. Thx very much!

**Comment by fnesveda** [comment]
Hi, thanks for the kind words, glad you like the app!

Have you tried setting the keys to `MK_BDN` and `MK_BUP` respectively? That should listen for the brighness keys on the Magic Keyboard (`fn + F1` and `fn + F2`).

Let me know if it helps!

<img width="523" src="https://github.com/fnesveda/ExternalDisplayBrightness/assets/2934111/b8cf859e-7554-404b-a09f-6058f050a46b">

**Comment by apaksoy** [comment]
Not sure what exactly MK_BDN and MK_BUP do, but they work, even when the "Change brightness ... " and "Require Command ..." boxes are not selected. 

Now, not only fn+F1 and fn+F2 decreases and increases brightness, respectively, but I can also utilize F1 and F2 keys within other shortcuts such as the Control+F2 shortcut which moves the focus to the menu bar in nearly all of the apps as usual. Awesome!!!

**Comment by fnesveda** [comment]
It's short for "Magic Keyboard Brightness DowN" and "Magic Keyboard Brightness UP" 🙂 Not the best naming, I know 😄
