### ISSUE TITLE
Security issue on Mojave

### ISSUE THREAD

**Issue by JTSawyer** [fnesveda/ExternalDisplayBrightness#3]
ExternalDisplayBrightness-1.2.0.dmg” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.

**Comment by fnesveda** [comment]
Hi,

thanks for the report, this is honestly strange behavior, I'm pretty sure I signed and notarized both the DMG file and the app inside. Can you please tell me where did you download the file from? From the website, or from this repo, or from somewhere else?

Also, could you please navigate to the directory containing the DMG file in Terminal, and send me the output of these three commands?
```
md5 ExternalDisplayBrightness-1.2.0.dmg
codesign -vvv --deep --strict ExternalDisplayBrightness-1.2.0.dmg
spctl -a -t open --context context:primary-signature -v ExternalDisplayBrightness-1.2.0.dmg
```

Thanks.

**Comment by fnesveda** [comment]
I'm going to close this, as there was no reply for a month and a half, plus I've verified with multiple users that the DMG opens for them just fine, so this was probably some random irreproducible problem.
