### ISSUE TITLE
Locks up with Macbook Pro 13" 2015 + AOC Q2778VQE

### ISSUE THREAD

**Issue by ahydronous** [fnesveda/ExternalDisplayBrightness#5]
What it says in the title. I have a [Macbook Pro 13" 2015](https://everymac.com/ultimate-mac-lookup/?search_keywords=a1502) on Catalina 10.15.1 (19B88) coupled with an [AOC Q2778VQE](https://eu.aoc.com/en/monitors/q2778vqe), connected over Thunderbolt 2 / Displayport.  
As soon as I try to lower or raise my brightness my entire Mac locks up.

If you look [here](http://aocmonitorap.com/upload_files/manual/Q2778VQE/English.pdf) on page 34 you can confirm the monitor supports DDC-CI

**Comment by hdmi** [comment]
Same behavior, with other supported screen.
I've been using DDC from the terminal since a lot a never had freezes, but with the app when I use the magic keyboard UP/DOWN shortcuts the laptop completely freezes.

**Comment by fnesveda** [comment]
Hi,

unfortunately, it seems like some Mac models just have these freezing issues, I'm trying to find a reason or notice a pattern, but I can't see one just yet. As a quick workaround, unplugging and replugging the display seems to unfreeze the system without the need to reboot (which would point perhaps to some corruption of the framebuffer).
Thanks for the report, though, I'll keep looking into this!

@hdmi When you say you've been using DDC from the terminal, you mean through [ddcctl](https://github.com/kfix/ddcctl)? Strange that that one works but not this one... Could you please try version [1.0.0](https://github.com/fnesveda/ExternalDisplayBrightness/releases/tag/v1.0.0) of this app to see if that one works? I've done some changes since then to increase compatibility with different displays, but maybe there were some regressions. Thanks!

**Comment by iroes** [comment]
+1. Macbook Pro 13" 2015 & HP Z27n display.

**Comment by iroes** [comment]
@fnesveda I've just tested it with the **ddcctl** software you mentioned in your comment. It worked right away. No issues whatsoever. I also tried the version 1.0.0 and froze exactly as if it were the latest 1.2.0.

**Comment by iroes** [comment]
Let me add that BOTH displays (the MBP one) and the external one freeze. I can access via SSH and run any command, but both displays would stay frozen until I force switch off and restart the computer. Of course I tried unplugging/plugging the external display to recover... uselessly.

**Comment by fnesveda** [comment]
@iroes Huh, I've read some reports from other people that unplugging the display seems to unfreeze the computer, maybe their computers froze for a different reason than yours. Not a great situation, to be honest.
When you used _ddcctl_, did you try just setting a brightness value to the display, or did you try reading it as well, like `ddcctl -d 1 -b "?"` I think the freezes are caused by the brightness reads, not the writes.

**Comment by iroes** [comment]
@fnesveda I've just tried. Yes, indeed, instant crash after reading. The terminal cursor blinked 5 or 6 times before completely freezing (weird?). I attach photo I've taken in case it helps:
![IMG_9640](https://user-images.githubusercontent.com/17746562/69425764-d5cda380-0d2b-11ea-8dea-f4032e5cf3cf.jpg)
.

**Comment by fnesveda** [comment]
Thanks!

I'm afraid I'm not able to fix this issue directly, it seems there could possibly be a bug somewhere in the graphics driver of some Mac models which makes the computer freeze when reading the external display's brightness over DDC. On my Mac, reading the brightness fails as well, but the Mac doesn't freeze, and for some people reading the brightness works normally.

The problem with ExternalDisplayBrightness is that before changing the brightness of the display, it reads the current brightness first, and then just raises or lowers that number a bit before sending it back to the display as the new brightness to set (and caches that new number for 10 seconds so it doesn't have to read it again in case of quick successive brightness changes). I'll probably add an option to the app to enable/disable reading the brightness before changing it, disabled by default, with a warning that enabling it could freeze their Macs, and let them decide if they want to try or not. This would avoid the freezes and at the same time offer people with compatible Macs and displays full functionality.

**Comment by iroes** [comment]
@fnesveda That would be so great! Also, as a suggestion, I'd consider completely removing the reading part as this DDC protocol seems to be implemented by vendors in a chaotic way. Maybe using it the less the better would help deal with the nightmare. I guess you can always store the last brightness set. Although I'm pretty sure there are many other implications that I'm not aware of. IDK, if s/o would set the brightness by other means (how dare they), then there would be a "brightness jump" when using your app. IDK, you're the one who knows. :)

**Comment by fnesveda** [comment]
@iroes I was considering it, yeah, but I don't think I want to remove the reading feature entirely, I know of some users for whom it actually works, so it would be an unnecessary regression for them. And I wish I was the one who knows, if I knew there will be so many issues I'd probably reconsider even releasing this in the first place. But, well, that's life.

Anyway, I've implemented the changes I talked about earlier, would you please be willing to test a [beta version](https://github.com/fnesveda/ExternalDisplayBrightness/files/3881330/ExternalDisplayBrightness-1.3.0-beta1.zip)? By default it should have the brightness reading disabled, so it shouldn't freeze your Mac, but if you enable it, then on the next brightness change your Mac will probably freeze again.

Thank you!

**Comment by iroes** [comment]
@fnesveda I've tested it. It's perfect. And I noticed that now it even caches the last set brightness for much more than 10 seconds :)). Thank you very much!

**Comment by fnesveda** [comment]
@iroes You're welcome!

The caching behavior is the same as before - if the app can read the brightness from the display, it will cache it for 10 seconds, if it can't read it, it will start at 50% and cache the brightness forever.

I'll release a new stable version with this change soon, but I want to take a stab at fixing the multiple identical display adressing issue first.

**Comment by Rubenfer** [comment]
Hi, same issue here. Mac mini 2018 freezes using a Philips 276E over HDMI.

**Comment by fnesveda** [comment]
@Rubenfer Hi,

yes, unfortunately, the 2018 Mac Mini has some issues with DDC/CI over the native HDMI port, multiple people have reported that. I'll have to expand the compatibility section on the website and in the Readme here on GitHub.

Unfortunately, I don't have this exact Mac myself, so I can't really debug this, but there is a workaround - if you have an USB-C to HDMI adapter, it should work fine with that.

**Comment by Rubenfer** [comment]
Yes, I have a USB-C hub with HDMI. I’ll try it. 
Moreover, I can buy a DisplayPort to usb-c cord to try.

**Comment by Rubenfer** [comment]
I just ordered it at Amazon. Tomorrow I'll say you if it works using DisplayPort to USB-C connection.

**Comment by Rubenfer** [comment]
Just for your information @fnesveda, DisplayPort to USB-C delivered and brightness control working fine in my Mac mini 2018.

**Comment by fnesveda** [comment]
@Rubenfer Thanks! Good to know, and I'm glad it works for you.

**Comment by fnesveda** [comment]
I've just published a new stable release, 1.3.0, which fixes this issue. If you're using the beta version from the earlier comments, I encourage you to update, as it incorporates additional fixes as well.
